### ISSUE TITLE
is there a way to play the latest / newest episode from a specific feed

### ISSUE THREAD

**Issue by kiil** [nboughton/yapa#1]
I've found out how to play a specific episode from a specific podcast / feed.

But is there a way to play the *latest / newest* episode from a specific feed.

USE CASE: I run a small script that shows me the weather, calendar items for the day, tasks, etc - and I would like it also to play the latest episode of a news podcast.

**Comment by nboughton** [comment]
Replace -f0 with the feed ID. However yapa rearranges the ID list to put the most recently updated feeds at the top so you may need to get creative in your script and grep for the feed name to get the right ID after each update.

` yapa play -f0 -e $(yapa list -f0 | tail -n1 | awk '{print $1}')`

**Comment by kiil** [comment]
This works! Thanks, a lot :)
