### ISSUE TITLE
Yappa Does not respond to playerctl / Media Keys

### ISSUE THREAD

**Issue by ghost** [nboughton/yapa#2]
The player responds to `XF86AudioPlay` / `playerctl play-pause` 
but not `XF86AudioPrev` / `playerctl previous` or `XF86AudioNext` / `playerctl next`
Not sure how to get more info to you, sorry!

**Comment by nboughton** [comment]
yapa has no function for next/prev skipping, the keys aren't mapped in the application. Play/pause presumably works because MPV supports the media keys but MPV is only passed one URL when it is invoked so it doesn't know about the rest of the queue.
